<a href="https://colab.research.google.com/github/jusmitha/hello-world/blob/main/2_NumPy(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1 style = "color:Red" >Working with NumPy</h1>


<h2 style = "color:Green"> Outcomes </h2>

#### At the end of this chapter, you will be able to
* Define NumPy data types
* Create and work with NumPy Arrays
* Understand the applications of NumpPy

<h2 style = "color:Green">What is Numpy?</h2>

* A Python package for scientific computations

* NumPy = ***Numerical Python***

* Numpy Library = Multi-dimensional array objects & Functions for processing it.

* Multi-dimensional object --> ___ndarray___ object

* Variaous operations supported: Arithmetic, Logical, Shape manipulation, Sort, DFT, Statistics, Random simulation etc.

* Importing NumPy: ___import numpy as np___

In [ ]:
# import numpy
import numpy as np

<h2 style = "color:Green"> Creating and Accessing ndarray object</h2>
    
* ndarray: Collection of items of the same type

    
* Items can be accessed using zero-based index.

    
* array() Function: ***numpy.array(object)*** 
                --> Creates an ndarray from an object.
                --> object: Any array or sequence.
               

<h3 style = "color:Blue">One Dimensional Array (Vector):</h3>

In [ ]:
# Create an one dimensional ndarray object from a list, display its values and type
n1=np.array([2 ,4, 6 ,8 ,10])
print(n1)
print(type(n1))

[ 2  4  6  8 10]
<class 'numpy.ndarray'>


In [ ]:
arr1=np.array([3,6,9,12,15,22])
print(arr1)
print(type(arr1))

[ 3  6  9 12 15 22]
<class 'numpy.ndarray'>


In [ ]:
# Create an one dimensional ndarray object from a tuple, display its values and type
import numpy as np
n2=np.array((3.2,4.5,6.7,8.9))
print(n2)
print(type(n2))


[3.2 4.5 6.7 8.9]
<class 'numpy.ndarray'>


In [ ]:
arr2=np.array((2.3,5.9,7.8,6.2))
print(arr2)
print(type(arr2))


[2.3 5.9 7.8 6.2]
<class 'numpy.ndarray'>


<h4 style = "color:Brown">Indexing & Slicing:</h4>

![oneDim.png](attachment:oneDim.png)

In [ ]:
# Create above one dimensional ndarray object and access its elements individually. And also slice some of its elements. 
arr=np.array([10,20,30,40])
print(arr[0])
print(arr[-4])
print(arr[1])
print(arr[-3])
print(arr[2])
print(arr[-2])
print(arr[3])
print(arr[-1])
print(arr[1:3:1])
print(arr[: : -1])

10
10
20
20
30
30
40
40
[20 30]
[40 30 20 10]


In [ ]:
arr=np.array([2,5,12,41])
print(arr[0])
print(arr[-4])
print(arr[1])
print(arr[-3])
print(arr[2])
print(arr[-2])
print(arr[3])
print(arr[-1])

2
2
5
5
12
12
41
41


<h3 style = "color:Blue">Two-Dimensional Arrays(Matrices)</h3>

* Each element  is itself 1D array


* arr2 = numpy.array([[row1], [row2], ...., [rowM]])


* Accessing an element: arr2[row_index, column_index]

In [ ]:
# Create a two dimensional array and access their rows and columns individually.
# Access the individual elements.
arr2 = np.array([[1, 2, 3], [5, 6, 7]])
print(arr2)
print(type(arr2))
print("First Row:\n",arr2[0])
print("First Row:\n",arr2[0,:])
print("Second Row:\n",arr2[1])
print("Second Row:\n",arr2[1,:])
print("Element at 2nd Row and 3rd column::\n",arr2[1,2])
print("column 1:\n",arr2[1,0])
print("column 2:\n",arr2[:,1])
print("column 0:\n",arr2[:,0])
print("second and third column:\n",arr2[:,1:3])

[[1 2 3]
 [5 6 7]]
<class 'numpy.ndarray'>
First Row:
 [1 2 3]
First Row:
 [1 2 3]
Second Row:
 [5 6 7]
Second Row:
 [5 6 7]
Element at 2nd Row and 3rd column::
 7
column 1:
 5
column 2:
 [2 6]
column 0:
 [1 5]
second and third column:
 [[2 3]
 [6 7]]


In [ ]:
n2 = np.array([[ 2, 3,4], [5, 6, 7]])
print(n2)
print(type(n2))

[[2 3 4]
 [5 6 7]]
<class 'numpy.ndarray'>


<h2 style = "color:Green">ndarray Attribtes</h2>

* ndarray.ndim: Number of dimensions


* ndarry.shape: Array dimensions as a tuple.


* ndarry.size: Total number of elements


* ndarry.dtype: Type of the array elements.


* ndarray.itemsize: The size of each element in bytes

In [ ]:
# Create an one dimensional ndarray object and diplay all its attribute values.
n3 = np.array([1,2,3,4])
print("Dimensions:",n3.ndim)
print("Shape:",n3.shape)
print("size:",n3.size)
print("Data Type:",n3.dtype)
print("Item Size:",n3.itemsize)

Dimensions: 1
Shape: (4,)
size: 4
Data Type: int32
Item Size: 4


In [ ]:
# Create a two dimensional ndarray object and diplay all its attribute values.
n4  = np.array([[10.0,20.0,30.0,40.0],[50.0,60.0,70.0,80.0],[90.0,100.0,110.0,120.0]])
print(n4)
print("Dimensions:",n4.ndim)
print("Shape:",n4.shape)
print("size:",n4.size)
print("Data Type:",n4.dtype)
print("Item Size:",n4.itemsize)

[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
Dimensions: 2
Shape: (3, 4)
size: 12
Data Type: int32
Item Size: 4


<h2 style = "color:Green">Other NumPy array creation functions</h2>

#### zeros(shape)
* Returns an array of zeros with specified shape
* Dafalut dtype is float



#### ones(shape)
* Returns an array of ones with specified shape
* Dafalut dtype is float


#### arange(start, stop, step, dtype)
* Returns an ndarray object with elements decided by start, stop and step arguments.
* Note that stop value is not including in the array.
* Default dtype is type is determined by type of start or stop values.

#### linspace(start, stop, N, dtype)
* Returns an ndarray object with N elements in the range from start value to stop stop .
* Note that stop value is inclusive in the array.
* Defaul type is float64

In [ ]:
# Create ndarray objects with all zeros using different dimensions and dtypes.
n=np.zeros((2,3))
print(n)
print(n.dtype)
n1=np.zeros((2,3),dtype=np.uint8)
print(n1)
print(n1.dtype)

[[0. 0. 0.]
 [0. 0. 0.]]
float64
[[0 0 0]
 [0 0 0]]
uint8


In [ ]:
# Create ndarray objects with all ones using different dimensions and dtypes.
n=np.ones((2,3),dtype=int)
print(n)

[[1 1 1]
 [1 1 1]]


In [ ]:
# Create one dimensional ndarray objects with various range of values and dtypes.
nar=np.arange(0,101,10,dtype=np.uint16)
print(nar)
print(nar.dtype)

[  0  10  20  30  40  50  60  70  80  90 100]
uint16


In [ ]:
# Create one dimensional ndarray objects with 25 elements between 1 and 100 of different dtypes.
n7=np.linspace(1,100,25)
print(n7)
print(len(n7))

[  1.      5.125   9.25   13.375  17.5    21.625  25.75   29.875  34.
  38.125  42.25   46.375  50.5    54.625  58.75   62.875  67.     71.125
  75.25   79.375  83.5    87.625  91.75   95.875 100.   ]
25
